config/routes.rb
TexterApp::Application.routes.draw do
  resources :messages
  resources :contacts
  root :to => 'messages#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :phone, presence: true, length: { is: 10 }
  has_many :recipients
  has_many :messages, through: :recipients
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, presence: true
  validates :from, presence: true
  has_many :recipients
  has_many :contacts, through: :recipients
  accepts_nested_attributes_for :recipients

  # def recipients_attributes=(attributes)

  # end
end

app/models/phone.rb
class Phone
  def self.format(number)
    if number.length == 10
      result = "("
      result += number[0,3]
      result +=  ") "
      result += number[3,3]
      result += "-"
      result += number[6,4]
    elsif number.length == 7
      result += number[0,3]
      result += "-"
      result += number[3,4]
    end
  end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :message
  belongs_to :contact

  before_create :send_message

  def message
    Message.find(self.message_id)
  end

  def contact
    Contact.find(self.contact_id)
  end

  private

    def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => self.message.body,
                      :To => self.contact.phone,
                      :From => self.message.from }
      ).execute
    rescue RestClient::BadRequest => error
      binding.pry
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/recipients_controller.rb
class RecipientsController < ApplicationController
  def create
    @recipient = Recipient.create(recipient_params)
  end

  private

  def recipient_params
    params.require(:recipient).permit(:contact_id, :message_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "#{@contact.name} was added to your contacts."
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      flash[:notice] = "#{@contact.name}'s info has been updated"
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    flash[:notice] = "#{@contact.name}'s entry has been deleted."
    redirect_to contacts_path
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
    @recipient = @message.recipients.new
    # 2.times { @message.recipients.build }
  end

  def create
    @message = Message.new(message_params)
    binding.pry
    if @message.save
      # 2.times do |i|
      #   if !@message.recipients.create(:contact_id => message_params[:recipients_attributes][i.to_s][:contact_id], :message_id => @message.id)
      #     render 'new'
      #   end
      # end
      flash[:notice] = "Your message was sent!"
      redirect_to messages_path
    else
      # 2.times { @message.recipients.build }
      render 'new'
    end
  end

  private

  def message_params
    params.require(:message).permit(:to, :from, :body, :recipients_attributes => [:contact_id, :message_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <h3>The following errors occured: </h3>
  <ul>
    <% @contact.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @contact do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone, "Phone Number" %>
    <%= f.text_field :phone, :class => 'form-control' %>
  </div>
  <%= f.submit :class => 'btn btn-warning' %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit <%= @contact.name %></h1>

<div class="form">
  <%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<h1>Your Contacts</h1>

<ul>
  <% @contacts.each do |contact| %>
    <li><%= link_to contact.name, contact_path(contact) %> - <%= Phone.format(contact.phone) %> </li>
  <% end %>
</ul>

<%= link_to "New Contact", new_contact_path, :class => 'btn btn-warning' %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<div class="form">
  <%= render('form') %>
</div>

<% link_to "Back to main menu", root_path %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p>Phone number: <%= Phone.format(@contact.phone) %></p>

<p><%= link_to "Edit this contact", edit_contact_path(@contact), :class => 'btn btn-warning' %></p>

<p><%= link_to "Delete this contact", contact_path(@contact), :class => 'btn btn-danger', :data => { :confirm => "Are you sure you want to delete #{@contact.name}?", :method => 'delete'} %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TexterApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Crafty+Girls' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <span class="logo"><%= link_to "Texty Text", root_path %></span>
</nav>

<div class="container">
  <%= flash[:notice] %>
  <%= yield %>
</div>

</body>
</html>

app/views/messages/index.html.erb
<h1>There are messages here, we swear!</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.id, message_path(message) %></li>
  <% end %>
</ul>

<%= link_to "New Message", new_message_path, :class => 'btn btn-danger' %>

<%= link_to "See your contacts", contacts_path, :class => 'btn btn-info' %>

app/views/messages/new.html.erb
<h1>New Message</h1>


<% if @message.errors.any? %>
  <h3>The following errors occured: </h3>
  <ul>
    <% @message.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>


  </ul>
<% end %>

<div class="form">
  <%= form_for @message, :class => 'form-inline' do |f| %>
    <div class="form-group">
      <%= f.fields_for :recipients do |t| %>
        <div class="form-group">
          <%= t.label :contact_id, "Recipient" %>
          <%= t.collection_select :contact_id, Contact.order(:name), :id, :name, :class => 'form-control' %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :from %>
     <%= f.collection_select :from, Contact.order(:name), :phone, :name, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, :class => 'form-control' %>
    </div>
    <%= f.submit :class => 'btn btn-danger' %>

  <% end %>
</div>
<br/>
<p><%= link_to "See your contacts", contacts_path, :class => 'btn btn-info' %></p>

app/views/messages/show.html.erb
<h2>Why hello, I am a message.</h2>

<p>This message is to:
<% @message.recipients.each do |recipient| %>
  <b><%= Phone.format(recipient.contact.phone) %></b>,
<% end %>
</p>

<p>This message is from: <b><%= Phone.format(@message.from) %></b></p>
<p>This message said, in its entirety: "<i><%= @message.body %></i>"</p>

<%= link_to "Flee this message for the safety of the message herd!", messages_path, class: 'btn btn-info' %>